#include <Wire.h>
#include <Adafruit_BNO08x.h>

// ============================================================
// BNO085 CONFIG
// ============================================================

#define BNO08X_RESET 5

Adafruit_BNO08x bno(BNO08X_RESET);
sh2_SensorValue_t sensorValue;

// Requested rates
constexpr uint32_t ACCEL_INTERVAL_US = 5000;   // 200 Hz
constexpr uint32_t GYRO_INTERVAL_US  = 5000;   // 200 Hz
constexpr uint32_t QUAT_INTERVAL_US  = 10000;  // 100 Hz


// ============================================================
// BINARY PROTOCOL V2
// ============================================================

constexpr uint8_t MAGIC0 = 0xA5;
constexpr uint8_t MAGIC1 = 0x5A;

constexpr uint8_t PROTOCOL_VERSION = 2;

enum PacketType : uint8_t {
  PKT_IMU   = 1,
  PKT_STATS = 2
};

enum ImuType : uint8_t {
  IMU_ACCEL = 1,
  IMU_GYRO  = 2,
  IMU_QUAT  = 3
};


// ============================================================
// RING BUFFER EVENT
// ============================================================
//
// 32 bytes/event
// 64 events = 2048 bytes RAM
//
// ============================================================

struct __attribute__((packed)) ImuEvent {

  // Timestamp generated by SH2/BNO085
  uint64_t sensor_timestamp_us;

  // Time at which Mega retrieved the event
  uint32_t host_timestamp_us;

  // SH2 sequence number
  uint8_t sensor_sequence;

  // Which virtual sensor
  uint8_t sensor_type;

  // BNO accuracy/status
  uint8_t sensor_status;

  // Number of values in v[]
  uint8_t n_values;

  float v[4];
};

static_assert(
  sizeof(ImuEvent) == 32,
  "Unexpected ImuEvent size"
);


// ============================================================
// SERIAL PACKET V2
// ============================================================
//
// EXACTLY 42 bytes
//
// ============================================================

struct __attribute__((packed)) SerialPacketV2 {

  uint8_t magic0;
  uint8_t magic1;

  uint8_t version;
  uint8_t packet_type;

  // Sequence of ALL transmitted packets
  uint32_t packet_sequence;

  // BNO085 native sensor timestamp
  uint64_t sensor_timestamp_us;

  // Mega timestamp when sensor event was retrieved
  uint32_t host_timestamp_us;

  // BNO / SH2 sequence
  uint8_t sensor_sequence;

  uint8_t sensor_type;

  // 0-3 accuracy/status for most sensors
  uint8_t sensor_status;

  uint8_t n_values;

  union {
    float f[4];
    uint32_t u32[4];
  } payload;

  uint16_t crc;
};

static_assert(
  sizeof(SerialPacketV2) == 42,
  "SerialPacketV2 must be 42 bytes"
);


// ============================================================
// RING BUFFER
// ============================================================

constexpr uint8_t IMU_BUFFER_SIZE = 64;
constexpr uint8_t IMU_BUFFER_MASK = IMU_BUFFER_SIZE - 1;

static_assert(
  (IMU_BUFFER_SIZE & (IMU_BUFFER_SIZE - 1)) == 0,
  "Buffer size must be power of two"
);

ImuEvent imuBuffer[IMU_BUFFER_SIZE];

uint8_t imuHead = 0;
uint8_t imuTail = 0;


// ============================================================
// DIAGNOSTIC COUNTERS
// ============================================================

uint32_t packetSequence = 0;

uint32_t imuReceived = 0;
uint32_t imuTransmitted = 0;

uint32_t imuOverflow = 0;

uint32_t unknownSensorEvents = 0;
uint32_t bnoResetCount = 0;

uint8_t maxQueueDepth = 0;


// ============================================================
// RING BUFFER HELPERS
// ============================================================

uint8_t imuQueueDepth() {

  return (
    imuHead - imuTail
  ) & IMU_BUFFER_MASK;
}


bool imuBufferEmpty() {

  return imuHead == imuTail;
}


bool imuBufferPush(
  const ImuEvent &event
) {

  uint8_t next =
    (imuHead + 1) & IMU_BUFFER_MASK;

  // Buffer full
  if (next == imuTail) {

    imuOverflow++;

    // Drop newest event.
    //
    // Existing chronological contents of
    // buffer remain intact.

    return false;
  }

  imuBuffer[imuHead] = event;

  imuHead = next;

  uint8_t depth = imuQueueDepth();

  if (depth > maxQueueDepth) {
    maxQueueDepth = depth;
  }

  return true;
}


bool imuBufferPeek(
  ImuEvent &event
) {

  if (imuBufferEmpty()) {
    return false;
  }

  event = imuBuffer[imuTail];

  return true;
}


void imuBufferRemove() {

  if (!imuBufferEmpty()) {

    imuTail =
      (imuTail + 1) & IMU_BUFFER_MASK;
  }
}


// ============================================================
// CRC16-CCITT
// ============================================================

uint16_t crc16_ccitt(
  const uint8_t *data,
  size_t length
) {

  uint16_t crc = 0xFFFF;

  while (length--) {

    crc ^= ((uint16_t)*data++) << 8;

    for (uint8_t i = 0; i < 8; i++) {

      if (crc & 0x8000) {

        crc =
          (crc << 1) ^ 0x1021;

      } else {

        crc <<= 1;
      }
    }
  }

  return crc;
}


// ============================================================
// BNO REPORT CONFIGURATION
// ============================================================

bool setReports() {

  bool ok = true;

  if (!bno.enableReport(
        SH2_ACCELEROMETER,
        ACCEL_INTERVAL_US
      )) {

    ok = false;
  }

  if (!bno.enableReport(
        SH2_GYROSCOPE_CALIBRATED,
        GYRO_INTERVAL_US
      )) {

    ok = false;
  }

  if (!bno.enableReport(
        SH2_ROTATION_VECTOR,
        QUAT_INTERVAL_US
      )) {

    ok = false;
  }

  return ok;
}


// ============================================================
// BNO ACQUISITION
// ============================================================

void serviceBNO() {

  // Drain every event currently waiting in SH2.
  //
  // Absolutely NO Serial.print() here.

  while (
    bno.getSensorEvent(&sensorValue)
  ) {

    imuReceived++;

    ImuEvent event;

    // Native BNO timestamp
    event.sensor_timestamp_us =
      sensorValue.timestamp;

    // Mega retrieval time
    event.host_timestamp_us =
      micros();

    // Native BNO report metadata
    event.sensor_sequence =
      sensorValue.sequence;

    event.sensor_status =
      sensorValue.status;

    event.v[0] = 0.0f;
    event.v[1] = 0.0f;
    event.v[2] = 0.0f;
    event.v[3] = 0.0f;


    switch (sensorValue.sensorId) {

      // ------------------------------------------------------
      // ACCELEROMETER
      // ------------------------------------------------------

      case SH2_ACCELEROMETER:

        event.sensor_type =
          IMU_ACCEL;

        event.n_values = 3;

        event.v[0] =
          sensorValue.un.accelerometer.x;

        event.v[1] =
          sensorValue.un.accelerometer.y;

        event.v[2] =
          sensorValue.un.accelerometer.z;

        imuBufferPush(event);

        break;


      // ------------------------------------------------------
      // GYROSCOPE
      // ------------------------------------------------------

      case SH2_GYROSCOPE_CALIBRATED:

        event.sensor_type =
          IMU_GYRO;

        event.n_values = 3;

        event.v[0] =
          sensorValue.un.gyroscope.x;

        event.v[1] =
          sensorValue.un.gyroscope.y;

        event.v[2] =
          sensorValue.un.gyroscope.z;

        imuBufferPush(event);

        break;


      // ------------------------------------------------------
      // ROTATION VECTOR
      // ------------------------------------------------------

      case SH2_ROTATION_VECTOR:

        event.sensor_type =
          IMU_QUAT;

        event.n_values = 4;

        event.v[0] =
          sensorValue.un.rotationVector.real;

        event.v[1] =
          sensorValue.un.rotationVector.i;

        event.v[2] =
          sensorValue.un.rotationVector.j;

        event.v[3] =
          sensorValue.un.rotationVector.k;

        imuBufferPush(event);

        break;


      default:

        unknownSensorEvents++;

        break;
    }
  }
}


// ============================================================
// BUILD IMU PACKET
// ============================================================

void makeImuPacket(
  const ImuEvent &event,
  SerialPacketV2 &packet
) {

  packet.magic0 = MAGIC0;
  packet.magic1 = MAGIC1;

  packet.version =
    PROTOCOL_VERSION;

  packet.packet_type =
    PKT_IMU;

  packet.packet_sequence =
    packetSequence++;

  packet.sensor_timestamp_us =
    event.sensor_timestamp_us;

  packet.host_timestamp_us =
    event.host_timestamp_us;

  packet.sensor_sequence =
    event.sensor_sequence;

  packet.sensor_type =
    event.sensor_type;

  packet.sensor_status =
    event.sensor_status;

  packet.n_values =
    event.n_values;

  for (uint8_t i = 0; i < 4; i++) {

    packet.payload.f[i] =
      event.v[i];
  }

  packet.crc = crc16_ccitt(
    reinterpret_cast<uint8_t *>(&packet),
    sizeof(SerialPacketV2) -
      sizeof(packet.crc)
  );
}


// ============================================================
// NON-BLOCKING SERIAL TRANSMISSION
// ============================================================

void serviceSerialTx() {

  constexpr uint8_t FRAME_SIZE =
    sizeof(SerialPacketV2);

  ImuEvent event;

  while (
    !imuBufferEmpty() &&
    Serial.availableForWrite() >= FRAME_SIZE
  ) {

    if (!imuBufferPeek(event)) {
      break;
    }

    SerialPacketV2 packet;

    makeImuPacket(
      event,
      packet
    );

    Serial.write(
      reinterpret_cast<uint8_t *>(&packet),
      FRAME_SIZE
    );

    // Only remove from ring after it has been
    // handed to the UART TX buffer.
    imuBufferRemove();

    imuTransmitted++;
  }
}


// ============================================================
// STATISTICS PACKET
// ============================================================

void serviceStats() {

  static uint32_t lastStatsMs = 0;

  uint32_t now = millis();

  if (
    (uint32_t)(now - lastStatsMs)
    < 1000
  ) {

    return;
  }

  if (
    Serial.availableForWrite() <
    sizeof(SerialPacketV2)
  ) {

    return;
  }

  lastStatsMs = now;

  SerialPacketV2 packet;

  packet.magic0 = MAGIC0;
  packet.magic1 = MAGIC1;

  packet.version =
    PROTOCOL_VERSION;

  packet.packet_type =
    PKT_STATS;

  packet.packet_sequence =
    packetSequence++;

  // Stats packet isn't associated with
  // one particular BNO sample.
  packet.sensor_timestamp_us = 0;

  packet.host_timestamp_us =
    micros();

  packet.sensor_sequence = 0;
  packet.sensor_type = 0;
  packet.sensor_status = 0;

  packet.n_values = 4;

  // --------------------------------------------
  // Stats payload
  //
  // [0] Arduino ring-buffer overflows
  // [1] maximum queue depth
  // [2] current queue depth
  // [3] BNO reset count
  // --------------------------------------------

  packet.payload.u32[0] =
    imuOverflow;

  packet.payload.u32[1] =
    maxQueueDepth;

  packet.payload.u32[2] =
    imuQueueDepth();

  packet.payload.u32[3] =
    bnoResetCount;

  packet.crc = crc16_ccitt(
    reinterpret_cast<uint8_t *>(&packet),
    sizeof(SerialPacketV2) -
      sizeof(packet.crc)
  );

  Serial.write(
    reinterpret_cast<uint8_t *>(&packet),
    sizeof(packet)
  );
}


// ============================================================
// SETUP
// ============================================================

void setup() {

  // Nice clean divisor on ATmega2560
  Serial.begin(500000);

  Wire.begin();

  Wire.setClock(400000);

  // ASCII here is okay.
  // Python synchronizes using A5 5A.
  Serial.println("BNO085 Protocol V2 starting");

  if (!bno.begin_I2C()) {

    Serial.println(
      "ERROR: BNO085 init failed"
    );

    while (1) {
      delay(100);
    }
  }

  Wire.setClock(400000);

  if (!setReports()) {

    Serial.println(
      "ERROR: report setup failed"
    );

    while (1) {
      delay(100);
    }
  }

  Serial.println(
    "BNO085 Protocol V2 streaming"
  );

  delay(100);
}


// ============================================================
// MAIN LOOP
// ============================================================

void loop() {

  // BNO085 can spontaneously reset.
  // Reports must then be re-enabled.
  if (bno.wasReset()) {

    bnoResetCount++;

    setReports();
  }

  // Highest priority
  serviceBNO();

  // Lower priority
  serviceSerialTx();

  // Diagnostics
  serviceStats();
}